# Static IP is assigned via Terraform cloud-init (vm_ip_address = 192.168.4.23/24).

[art_hosts]
art-host ansible_host=192.168.4.200

[art_hosts:vars]
ansible_user=art
ansible_private_key_file=~/.ssh/id_ed25519
